name: Run Tests

on:
  pull_request:
    branches:
      - main # Target branch for the tests
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (example for a JS project)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Upload Test Results (Optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results
